### ISSUE TITLE
SwinIR Problem

### ISSUE THREAD

**Issue by yileijin** [renaissanceee/Mipmap-GS#2]
Nice work. I followed the instructions and downloaded the required CKPT, but there were something wrong when I ran "python pseudo_GT/SwinIR/run_swinir_360.py". There seem to be some problems with the SwinIR ckpts.

Here are the errors:
UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/root/autodl-tmp/Mipmap-GS/pseudo_GT/SwinIR/main_test_swinir.py", line 327, in <module>
    main()
  File "/root/autodl-tmp/Mipmap-GS/pseudo_GT/SwinIR/main_test_swinir.py", line 47, in main
    model = define_model(args)
            ^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/Mipmap-GS/pseudo_GT/SwinIR/main_test_swinir.py", line 202, in define_model
    model.load_state_dict(pretrained_model[param_key_g] if param_key_g in pretrained_model.keys() else pretrained_model, strict=True)
  File "/root/autodl-tmp/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SwinIR:
        Unexpected key(s) in state_dict: "upsample.4.weight", "upsample.4.bias". 
loading model from pseudo_GT/SwinIR/model_zoo/swinir/001_classicalSR_DF2K_s64w8_SwinIR-M_x8.pth
/root/autodl-tmp/env/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

**Comment by renaissanceee** [comment]
Please download the correct ckpt, see [here](https://github.com/renaissanceee/Mipmap-GS/blob/main/pseudo_GT/SwinIR/model_zoo/swinir/ckpt.txt#L1).
